-- Create the skills table
CREATE TABLE public.skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create the levels table
CREATE TABLE public.levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add comments for clarity
COMMENT ON TABLE public.skills IS 'Stores the different skills available for courses and user profiles.';
COMMENT ON TABLE public.levels IS 'Stores the different skill levels (e.g., Beginner, Intermediate).';

-- Enable Row Level Security
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.levels ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- Authenticated users can read skills
CREATE POLICY "Allow authenticated users to read skills"
ON public.skills
FOR SELECT
TO authenticated
USING (true);

-- Authenticated users can read levels
CREATE POLICY "Allow authenticated users to read levels"
ON public.levels
FOR SELECT
TO authenticated
USING (true);

-- Insert initial data into the skills table
INSERT INTO public.skills (name) VALUES
('Web Development'),
('Mobile App Development'),
('Data Science'),
('Artificial Intelligence'),
('Cybersecurity'),
('UI/UX Design'),
('Game Development'),
('Cloud Computing');

-- Insert initial data into the levels table
INSERT INTO public.levels (name) VALUES
('Beginner'),
('Intermediate'),
('Advanced'),
('Expert');
